from easydict import EasyDict as edict
import yaml

"""
Default config for the SRBT PET-Track tracker.
"""
cfg = edict()

# MODEL
cfg.MODEL = edict()
cfg.MODEL.PRETRAIN_FILE = "mae_pretrain_vit_base.pth"
cfg.MODEL.PRETRAIN_PATH = ""
cfg.MODEL.PRETRAINED_BASELINE_CKPT = ""
cfg.MODEL.PRETRAINED_SRBT_CKPT = ""
cfg.MODEL.PRETRAINED_EXPERT_CKPT = ""
cfg.MODEL.INIT_CHECKPOINT = ""
cfg.MODEL.RETURN_INTER = False
cfg.MODEL.RETURN_STAGES = []

# MODEL.BACKBONE
cfg.MODEL.BACKBONE = edict()
cfg.MODEL.BACKBONE.TYPE = "vit_base_patch16_224"
cfg.MODEL.BACKBONE.STRIDE = 16
cfg.MODEL.BACKBONE.MID_PE = False
cfg.MODEL.BACKBONE.SEP_SEG = False
cfg.MODEL.BACKBONE.CAT_MODE = 'direct'
cfg.MODEL.BACKBONE.MERGE_LAYER = 0
cfg.MODEL.BACKBONE.ADD_CLS_TOKEN = False
cfg.MODEL.BACKBONE.CLS_TOKEN_USE_MODE = 'ignore'

cfg.MODEL.BACKBONE.CE_LOC = []
cfg.MODEL.BACKBONE.CE_KEEP_RATIO = []
cfg.MODEL.BACKBONE.CE_TEMPLATE_RANGE = 'ALL'  # choose between ALL, CTR_POINT, CTR_REC, GT_BOX

# MODEL.HEAD
cfg.MODEL.HEAD = edict()
cfg.MODEL.HEAD.TYPE = "CENTER"
cfg.MODEL.HEAD.NUM_CHANNELS = 256

# MODEL.MEMORY
cfg.MODEL.MEMORY = edict()
# ATU
cfg.MODEL.MEMORY.ATU_BETA = 4.0
# AMAH
cfg.MODEL.MEMORY.AMAH_BETA = 4.0
cfg.MODEL.MEMORY.AMAH_LAYERS = []
cfg.MODEL.MEMORY.AMAH_SP_LAYERS = []

# MODEL.EXPERT
cfg.MODEL.EXPERT = edict()
cfg.MODEL.EXPERT.ENABLE = False
cfg.MODEL.EXPERT.DEFAULT = "generalist"
cfg.MODEL.EXPERT.NAMES = [
    "generalist",
    "motion_fm",
    "precision_refiner",
    "visibility_foc_ov",
    "discrimination_bi",
]
cfg.MODEL.EXPERT.ACTIVATOR_HIDDEN_DIM = 64
cfg.MODEL.EXPERT.ACTIVATION_THRESHOLD = 0.5
cfg.MODEL.EXPERT.MAX_ACTIVE_SPECIALISTS = 2
cfg.MODEL.EXPERT.ACTIVATOR_TRAINED = False
cfg.MODEL.EXPERT.USE_ACTIVATION_INFERENCE = False

cfg.MODEL.SEARCH_CONTROLLER = edict()
cfg.MODEL.SEARCH_CONTROLLER.ENABLE = False
cfg.MODEL.SEARCH_CONTROLLER.HIDDEN_DIM = 64
cfg.MODEL.SEARCH_CONTROLLER.MAX_CENTER_STEP = 1.0
cfg.MODEL.SEARCH_CONTROLLER.TRAINED = False
cfg.MODEL.SEARCH_CONTROLLER.USE_INFERENCE = False

cfg.MODEL.REDETECT = edict()
cfg.MODEL.REDETECT.LAMBDA_H = 1.0          # weight of the event reappear prior
cfg.MODEL.REDETECT.USE_TEMPLATE_CONDITIONING = True
cfg.MODEL.REDETECT.USE_PRIOR_GATE = True   # gate architecture when a trained prior is enabled
cfg.MODEL.REDETECT.USE_PRIOR = False       # enable only after prior-conditioned training
cfg.MODEL.REDETECT.TRAINED_WITH_PRIOR = False
cfg.MODEL.REDETECT.TRAIN_SEARCH_FACTOR = 8.0  # large crop used to train global redetection
cfg.MODEL.REDETECT.IDENTITY_DIM = 128
cfg.MODEL.REDETECT.IDENTITY_THRESHOLD = 0.75
cfg.MODEL.REDETECT.ACCEPTANCE_THRESHOLD = 0.50
cfg.MODEL.REDETECT.EVENT_TOP_K = 5
cfg.MODEL.REDETECT.EVENT_NMS_RADIUS = 12
cfg.MODEL.REDETECT.EVENT_MIN_ROBUST_SCORE = 3.0
cfg.MODEL.REDETECT.RECOVERY_SEARCH_FACTOR = 5.0
cfg.MODEL.REDETECT.FULL_RGB_FALLBACK_INTERVAL = 10

# DART reliability gates, duration decoder, and recovery hypothesis lifecycle.
cfg.MODEL.SRBT = edict()
cfg.MODEL.SRBT.ENABLE = False
cfg.MODEL.SRBT.GATE = edict()
cfg.MODEL.SRBT.GATE.HIDDEN_DIM = 128
cfg.MODEL.SRBT.GATE.RESPONSE_DIM = 3
cfg.MODEL.SRBT.GATE.LOCALIZATION_HIDDEN_DIM = 32
cfg.MODEL.SRBT.HYPOTHESES = edict()
cfg.MODEL.SRBT.HYPOTHESES.IDENTITY_DIM = 64
cfg.MODEL.SRBT.HYPOTHESES.K_MAX = 5
cfg.MODEL.SRBT.HYPOTHESES.CUMULATIVE_MASS = 0.9
cfg.MODEL.SRBT.HYPOTHESES.IDENTITY_COST = 0.6
cfg.MODEL.SRBT.HYPOTHESES.BOX_COST = 0.4
cfg.MODEL.SRBT.HYPOTHESES.MIN_IDENTITY = 0.4
cfg.MODEL.SRBT.HYPOTHESES.MAX_CENTER_DISTANCE = 0.5
cfg.MODEL.SRBT.HYPOTHESES.MERGE_IOU = 0.7
cfg.MODEL.SRBT.HYPOTHESES.MERGE_IDENTITY = 0.8
cfg.MODEL.SRBT.HYPOTHESES.PREVIOUS_WEIGHT = 0.7
cfg.MODEL.SRBT.HYPOTHESES.OBSERVATION_WEIGHT = 0.3
cfg.MODEL.SRBT.HYPOTHESES.MISS_DECAY = 0.85
cfg.MODEL.SRBT.HYPOTHESES.MIN_WEIGHT = 0.05
cfg.MODEL.SRBT.HYPOTHESES.MAX_AGE = 32
cfg.MODEL.SRBT.CONTROLLER = edict()
cfg.MODEL.SRBT.CONTROLLER.THETA_OBSERVABLE = 0.70
cfg.MODEL.SRBT.CONTROLLER.THETA_LOCALIZED = 0.70
cfg.MODEL.SRBT.CONTROLLER.THETA_RECOVER = 0.75
cfg.MODEL.SRBT.CONTROLLER.LOCAL_DURATION = 2
cfg.MODEL.SRBT.CONTROLLER.GLOBAL_DURATION = 4
cfg.MODEL.SRBT.CONTROLLER.VERIFY_DURATION = 2
cfg.MODEL.SRBT.CONTROLLER.LONG_STABLE_DURATION = 5
cfg.MODEL.SRBT.CONTROLLER.HIDDEN_DIM = 16

# TRAIN
cfg.TRAIN = edict()
cfg.TRAIN.LR = 0.0001
cfg.TRAIN.WEIGHT_DECAY = 0.0001
cfg.TRAIN.EPOCH = 500
cfg.TRAIN.LR_DROP_EPOCH = 400
cfg.TRAIN.BATCH_SIZE = 16
cfg.TRAIN.NUM_WORKER = 8
cfg.TRAIN.PIN_MEMORY = True
cfg.TRAIN.PERSISTENT_WORKERS = False
cfg.TRAIN.OPTIMIZER = "ADAMW"
cfg.TRAIN.BACKBONE_MULTIPLIER = 0.1
cfg.TRAIN.GIOU_WEIGHT = 2.0
cfg.TRAIN.L1_WEIGHT = 5.0
cfg.TRAIN.FOCAL_WEIGHT = 1.0
cfg.TRAIN.EXPERT_ADVANTAGE_WEIGHT = 1.0
cfg.TRAIN.EXPERT_ADVANTAGE_MARGIN = 0.10
cfg.TRAIN.SMALL_TARGET_CENTER_RANK_WEIGHT = 1.0
cfg.TRAIN.SMALL_TARGET_MATCH_RANK_WEIGHT = 0.0
cfg.TRAIN.SMALL_TARGET_DENSE_SIZE_WEIGHT = 0.0
cfg.TRAIN.SMALL_TARGET_DENSE_OFFSET_WEIGHT = 0.0
cfg.TRAIN.SMALL_TARGET_SOFT_BOX_TEMPERATURE = 0.0
cfg.TRAIN.SMALL_TARGET_ADAPTER_LR = 0.0
cfg.TRAIN.FREEZE_LAYERS = [0, ]
cfg.TRAIN.PRINT_INTERVAL = 50
cfg.TRAIN.VAL_EPOCH_INTERVAL = 5
cfg.TRAIN.VAL_LAST_EPOCHS = 0
cfg.TRAIN.VAL_START_EPOCH = 70
cfg.TRAIN.VAL_SCHEDULE = [[70, 79, 5], [80, 89, 3], [90, -1, 1]]
cfg.TRAIN.SEQUENCE_VAL_ENABLE = False
cfg.TRAIN.SEQUENCE_VAL_SCHEDULE = []
cfg.TRAIN.SEQUENCE_VAL_TRAIN_IOU_THRESHOLD = 0.0
cfg.TRAIN.GRAD_CLIP_NORM = 0.1
cfg.TRAIN.AMP = False
cfg.TRAIN.AMP_DTYPE = "float16"
cfg.TRAIN.STAGE = "srbt"
cfg.TRAIN.EXPERT_PHASE = "specialize"
cfg.TRAIN.DART_DECODER_ONLY = False
cfg.TRAIN.PURSUIT_LR = 1e-4
cfg.TRAIN.ACTIVATOR_LR = 1e-4
cfg.TRAIN.ACTIVATOR_ADVANTAGE_MARGIN = 0.02
cfg.TRAIN.ACTIVATOR_POS_WEIGHT = [1.0, 1.0, 1.0, 1.0]
cfg.TRAIN.PURSUIT_CENTER_WEIGHT = 1.0
cfg.TRAIN.PURSUIT_SCALE_WEIGHT = 0.5
cfg.TRAIN.PURSUIT_CONTAINMENT_WEIGHT = 2.0
cfg.TRAIN.PURSUIT_INSIDE_WEIGHT = 0.5
cfg.TRAIN.PURSUIT_QUALITY_WEIGHT = 0.25
cfg.TRAIN.MOTION_DISPLACEMENT_WEIGHT = 1.0
cfg.TRAIN.DISCRIMINATION_RANKING_WEIGHT = 1.0
cfg.TRAIN.DISCRIMINATION_RANKING_MARGIN = 0.2
cfg.TRAIN.SPECIALIST_EXPERT_IDS = [1, 2, 3, 4]
cfg.TRAIN.SPECIALIST_EXPERT_SCHEDULE = []
cfg.TRAIN.MIN_EPOCH = 25
cfg.TRAIN.REFINE_MAX_EPOCH = 12
cfg.TRAIN.REFINE_TAIL_LR = 1e-6
cfg.TRAIN.REFINE_MEMORY_LR = 5e-7
cfg.TRAIN.REFINE_SEQUENCE_VAL_SCHEDULE = [[1, -1, 1]]
cfg.TRAIN.LOAD_LATEST = True
cfg.TRAIN.REBASE_SCHEDULER_ON_RESUME = False
cfg.TRAIN.BASE_LR_MULTIPLIER_IN_ALL = 0.1
cfg.TRAIN.SAVE_EPOCH_INTERVAL = 50
cfg.TRAIN.SAVE_LAST_EPOCHS = 3
cfg.TRAIN.SAVE_EPOCHS = [79, 159, 239]
cfg.TRAIN.SAVE_LATEST_EACH_EPOCH = True
cfg.TRAIN.EXPERT_LR_MULTIPLIER = 5.0
cfg.TRAIN.SAVE_FINAL_CHECKPOINT = False
cfg.TRAIN.SAVE_BEST = False
cfg.TRAIN.BEST_LOADER = "val"
cfg.TRAIN.BEST_METRIC = "IoU"
cfg.TRAIN.BEST_METRIC_MODE = "max"
cfg.TRAIN.SPECIALIST_GATE_ENABLE = False
cfg.TRAIN.SPECIALIST_MIN_COUNT = 100
cfg.TRAIN.SPECIALIST_MIN_DELTA = 0.02
cfg.TRAIN.GENERALIST_REFERENCE_IOU = -1.0
cfg.TRAIN.GENERALIST_MAX_DROP = 0.005
cfg.TRAIN.VISIBILITY_REFERENCE_REAPPEAR_IOU = -1.0
cfg.TRAIN.VISIBILITY_REFERENCE_REAPPEAR_SUCCESS = -1.0
cfg.TRAIN.VISIBILITY_REFERENCE_RGB_FALSE_ACCEPT_RATE = -1.0

# Presence gate supervision.
cfg.TRAIN.SRBT_LOSS = edict()
cfg.TRAIN.SRBT_LOSS.EXISTENCE_WEIGHT = 1.0
cfg.TRAIN.SRBT_LOSS.FOCAL_GAMMA = 2.0
cfg.TRAIN.RECOVERY_LOSS = edict()
cfg.TRAIN.RECOVERY_LOSS.IDENTITY_WEIGHT = 1.0
cfg.TRAIN.RECOVERY_LOSS.RANKING_WEIGHT = 0.5
cfg.TRAIN.RECOVERY_LOSS.RANKING_MARGIN = 0.2
cfg.TRAIN.DART_LOSS = edict()
cfg.TRAIN.DART_LOSS.COVERAGE_WEIGHT = 1.0
cfg.TRAIN.DART_LOSS.GEOMETRY_WEIGHT = 1.0
cfg.TRAIN.DART_LOSS.RANKING_WEIGHT = 0.5
cfg.TRAIN.DART_LOSS.RANKING_MARGIN = 0.2
cfg.TRAIN.DART_LOSS.DECODER_WEIGHT = 1.0
cfg.TRAIN.CE_START_EPOCH = 20  # candidate elimination start epoch
cfg.TRAIN.CE_WARM_EPOCH = 80  # candidate elimination warm up epoch
cfg.TRAIN.DROP_PATH_RATE = 0.1  # drop path rate for ViT backbone

# TRAIN.SCHEDULER
cfg.TRAIN.SCHEDULER = edict()
cfg.TRAIN.SCHEDULER.TYPE = "step"
cfg.TRAIN.SCHEDULER.DECAY_RATE = 0.1
cfg.TRAIN.SCHEDULER.MILESTONES = [50, 80]
cfg.TRAIN.SCHEDULER.GAMMA = 0.1

# DATA
cfg.DATA = edict()
cfg.DATA.SAMPLER_MODE = "causal"  # sampling methods
cfg.DATA.MEAN = [0.485, 0.456, 0.406]
cfg.DATA.STD = [0.229, 0.224, 0.225]
cfg.DATA.MAX_SAMPLE_INTERVAL = 200
cfg.DATA.SRBT = edict()
cfg.DATA.SRBT.ENABLE = False
cfg.DATA.SRBT.ANCHOR_WEIGHTS = edict()
cfg.DATA.SRBT.ANCHOR_WEIGHTS.VISIBLE = 0.25
cfg.DATA.SRBT.ANCHOR_WEIGHTS.PRESENT_TO_ABSENT = 0.25
cfg.DATA.SRBT.ANCHOR_WEIGHTS.ABSENT = 0.25
cfg.DATA.SRBT.ANCHOR_WEIGHTS.REAPPEARING = 0.25
cfg.DATA.CHALLENGE_SAMPLING = edict()
cfg.DATA.CHALLENGE_SAMPLING.ENABLE = False
cfg.DATA.CHALLENGE_SAMPLING.PRECISE = False
cfg.DATA.CHALLENGE_SAMPLING.MANIFEST = ""
cfg.DATA.CHALLENGE_SAMPLING.VAL_MANIFEST = ""
cfg.DATA.PURSUIT = edict()
cfg.DATA.PURSUIT.ENABLE = False
cfg.DATA.PURSUIT.WINDOW_LENGTH = 8
cfg.DATA.PURSUIT.CANVAS_SIZE = 352
cfg.DATA.PURSUIT.TRANSITION_PROBABILITY = 0.5
cfg.DATA.PURSUIT.REAPPEAR_PROBABILITY = 0.25
# DATA.TRAIN
cfg.DATA.TRAIN = edict()
cfg.DATA.TRAIN.DATASETS_NAME = ["LASOT", "GOT10K_vottrain"]
cfg.DATA.TRAIN.DATASETS_RATIO = [1, 1]
cfg.DATA.TRAIN.SAMPLE_PER_EPOCH = 60000
# DATA.VAL
cfg.DATA.VAL = edict()
cfg.DATA.VAL.DATASETS_NAME = ["GOT10K_votval"]
cfg.DATA.VAL.DATASETS_RATIO = [1]
cfg.DATA.VAL.SAMPLE_PER_EPOCH = 10000
# DATA.SEARCH
cfg.DATA.SEARCH = edict()
cfg.DATA.SEARCH.SIZE = 320
cfg.DATA.SEARCH.FACTOR = 5.0
cfg.DATA.SEARCH.CENTER_JITTER = 4.5
cfg.DATA.SEARCH.SCALE_JITTER = 0.5
cfg.DATA.SEARCH.MOTION_CENTER_JITTER_MULTIPLIER = 1.0
cfg.DATA.SEARCH.PRECISION_SCALE_MULTIPLIER = 1.0
cfg.DATA.SEARCH.NUMBER = 1
# DATA.TEMPLATE
cfg.DATA.TEMPLATE = edict()
cfg.DATA.TEMPLATE.NUMBER = 1
cfg.DATA.TEMPLATE.SIZE = 128
cfg.DATA.TEMPLATE.FACTOR = 2.0
cfg.DATA.TEMPLATE.CENTER_JITTER = 0
cfg.DATA.TEMPLATE.SCALE_JITTER = 0

# TEST
cfg.TEST = edict()
cfg.TEST.TEMPLATE_FACTOR = 2.0
cfg.TEST.TEMPLATE_SIZE = 128
cfg.TEST.SEARCH_FACTOR = 5.0
cfg.TEST.SEARCH_SIZE = 320
cfg.TEST.EPOCH = 500
cfg.TEST.SHORTTERM_LIBRARY_NUMS = 5
cfg.TEST.LONGTERM_LIBRARY_NUMS = 10
cfg.TEST.SAMPLE_INTERVAL = 5
cfg.TEST.UPDATE_INTERVAL = 10
cfg.TEST.LOWER_BOUND = 0.35
cfg.TEST.SCORE_THRESHOLD = 0.7
cfg.TEST.ABSENT_SCORE_THRESHOLD = 0.2
cfg.TEST.ABSENT_CONFIDENCE_THRESHOLD = 0.0
cfg.TEST.CHECKPOINT = ""
cfg.TEST.POLICY_MODE = "stateful"


def _edict2dict(dest_dict, src_edict):
    if isinstance(dest_dict, dict) and isinstance(src_edict, dict):
        for k, v in src_edict.items():
            if not isinstance(v, edict):
                dest_dict[k] = v
            else:
                dest_dict[k] = {}
                _edict2dict(dest_dict[k], v)
    else:
        return


def gen_config(config_file):
    cfg_dict = {}
    _edict2dict(cfg_dict, cfg)
    with open(config_file, 'w') as f:
        yaml.dump(cfg_dict, f, default_flow_style=False)


def _update_config(base_cfg, exp_cfg):
    if isinstance(base_cfg, dict) and isinstance(exp_cfg, edict):
        for k, v in exp_cfg.items():
            if k in base_cfg:
                if not isinstance(v, dict):
                    base_cfg[k] = v
                else:
                    _update_config(base_cfg[k], v)
            else:
                raise ValueError("{} not exist in config.py".format(k))
    else:
        return


# def update_config_from_file(filename, base_cfg=None):
#     exp_config = None
#     with open(filename) as f:
#         exp_config = edict(yaml.safe_load(f))
#         if base_cfg is not None:
#             _update_config(base_cfg, exp_config)
#         else:
#             _update_config(cfg, exp_config)


def update_config_from_file(filename, base_cfg=None):
    exp_config = None
    # 閺勬儳绱￠幐鍥х暰缂傛牜鐖滄稉?utf-8
    with open(filename, 'r', encoding='utf-8') as f:
        exp_config = edict(yaml.safe_load(f))
        if "PET_LOSS" in exp_config.get("TRAIN", {}):
            raise ValueError(
                "legacy TRAIN.PET_LOSS is removed; use TRAIN.SRBT_LOSS")
        if base_cfg is not None:
            _update_config(base_cfg, exp_config)
        else:
            _update_config(cfg, exp_config)
